export const locations = [
  {
    code: "BAR",
    name: "Baringo",
    constituencies: [
      "Baringo Central",
      "Baringo North",
      "Baringo South",
      "Eldama Ravine",
      "Mogotio",
      "Tiaty",
    ],
  },
  {
    code: "BOM",
    name: "Bomet",
    constituencies: [
      "Bomet Central",
      "Bomet East",
      "Chepalungu",
      "Konoin",
      "Sotik",
    ],
  },
  {
    code: "BUN",
    name: "Bungoma",
    constituencies: [
      "Bumula",
      "Bungoma East",
      "Bungoma North",
      "Bungoma South",
      "Bungoma West",
      "Kanduyi",
      "Kimilili",
      "Mt. Elgon",
      "Sirisia",
      "Tongaren",
      "Webuye East",
      "Webuye West",
    ],
  },
  {
    code: "BUS",
    name: "Busia",
    constituencies: [
      "Budalangi",
      "Bunyala",
      "Butula",
      "Funyula",
      "Matayos",
      "Nambale",
      "Teso North",
      "Teso South",
    ],
  },
  {
    code: "EMA",
    name: "Elgeyo-Marakwet",
    constituencies: [
      "Keiyo North",
      "Keiyo South",
      "Marakwet East",
      "Marakwet West",
    ],
  },
  {
    code: "EMA",
    name: "Embu",
    constituencies: [
      "Embu East",
      "Embu North",
      "Embu West",
      "Manyatta",
      "Mbeere North",
      "Mbeere South",
      "Runyenjes",
    ],
  },
  {
    code: "GAR",
    name: "Garissa",
    constituencies: [
      "Balambala",
      "Dadaab",
      "Fafi",
      "Garissa Township",
      "Hulugho",
      "Ijara",
      "Lagdera",
    ],
  },
  {
    code: "HOM",
    name: "Homabay",
    constituencies: [
      "Kabondo Kasipul",
      "Karachuonyo",
      "Kasipul",
      "Ndhiwa",
      "Rangwe",
      "Suba North",
      "Suba South",
    ],
  },
  {
    code: "ISI",
    name: "Isiolo",
    constituencies: ["Isiolo North", "Isiolo South", "Isiolo West"],
  },
  {
    code: "KAJ",
    name: "Kajiado",
    constituencies: [
      "Kajiado Central",
      "Kajiado East",
      "Kajiado North",
      "Kajiado West",
      "Loitokitok",
      "Magadi",
    ],
  },
  {
    code: "KAK",
    name: "Kakamega",
    constituencies: [
      "Butere",
      "Kabuchai",
      "Kakamega Central",
      "Kakamega East",
      "Kakamega North",
      "Kakamega South",
      "Khwisero",
      "Lugari",
      "Lurambi",
      "Malava",
      "Matungu",
      "Mumias East",
      "Mumias West",
      "Navakholo",
    ],
  },
  {
    code: "KER",
    name: "Kericho",
    constituencies: [
      "Ainamoi",
      "Belgut",
      "Bureti",
      "Kipkelion East",
      "Kipkelion West",
      "Sigowet–Soin",
    ],
  },
  {
    code: "KIL",
    name: "Kilifi",
    constituencies: [
      "Ganze",
      "Kaloleni",
      "Kilifi North",
      "Kilifi South",
      "Magarini",
      "Malindi",
      "Rabai",
    ],
  },
  {
    code: "KIR",
    name: "Kirinyaga",
    constituencies: [
      "Gichugu",
      "Kirinyaga Central",
      "Kirinyaga East",
      "Kirinyaga West",
      "Mwea",
    ],
  },
  {
    code: "KIS",
    name: "Kisii",
    constituencies: [
      "Bobasi",
      "Bomachoge Borabu",
      "Bomachoge Chache",
      "Kitutu Chache North",
      "Kitutu Chache South",
      "Nyamira North",
      "Nyamira South",
      "South Mugirango",
    ],
  },
  {
    code: "KIS",
    name: "Kisumu",
    constituencies: [
      "Kisumu Central",
      "Kisumu East",
      "Kisumu West",
      "Muhoroni",
      "Nyakach",
      "Nyando",
      "Seme",
    ],
  },
  {
    code: "KIT",
    name: "Kitui",
    constituencies: [
      "Kitui Central",
      "Kitui East",
      "Kitui Rural",
      "Kitui South",
      "Kitui West",
      "Mwingi Central",
      "Mwingi North",
      "Mwingi West",
    ],
  },
  {
    code: "KWA",
    name: "Kwale",
    constituencies: ["Kinango", "Lunga Lunga", "Matuga", "Msambweni"],
  },
  {
    code: "LAI",
    name: "Laikipia",
    constituencies: [
      "Laikipia East",
      "Laikipia North",
      "Laikipia West",
      "Nyahururu",
    ],
  },
  {
    code: "LAM",
    name: "Lamu",
    constituencies: ["Lamu East", "Lamu West"],
  },
  {
    code: "MAC",
    name: "Machakos",
    constituencies: [
      "Athi River",
      "Kangundo",
      "Kathiani",
      "Machakos Town",
      "Masinga",
      "Matungulu",
      "Mavoko",
      "Mwala",
      "Yatta",
    ],
  },
  {
    code: "MAK",
    name: "Makueni",
    constituencies: [
      "Kaiti",
      "Kibwezi East",
      "Kibwezi West",
      "Kilome",
      "Makueni",
      "Mbooni East",
      "Mbooni West",
    ],
  },
  {
    code: "MAN",
    name: "Mandera",
    constituencies: [
      "Banissa",
      "Lafey",
      "Mandera East",
      "Mandera North",
      "Mandera South",
      "Mandera West",
    ],
  },
  {
    code: "MER",
    name: "Meru",
    constituencies: [
      "Buuri",
      "Igembe Central",
      "Igembe North",
      "Igembe South",
      "Imenti Central",
      "Imenti North",
      "Imenti South",
      "Meru Central",
      "Meru North",
      "Meru South",
      "Tigania East",
      "Tigania West",
    ],
  },
  {
    code: "MIG",
    name: "Migori",
    constituencies: [
      "Kuria East",
      "Kuria West",
      "Nyatike",
      "Rongo",
      "Suna East",
      "Suna West",
      "Uriri",
    ],
  },
  {
    code: "MUR",
    name: "Murang'a",
    constituencies: [
      "Gatanga",
      "Kahuro",
      "Kandara",
      "Kangema",
      "Kigumo",
      "Kiharu",
      "Mathioya",
      "Murang'a East",
      "Murang'a South",
      "Kangema",
      "Kigumo",
      "Kiharu",
      "Mathioya",
      "Murang'a East",
      "Murang'a South",
    ],
  },
  {
    code: "MOM",
    name: "Mombasa",
    constituencies: [
      "Changamwe",
      "Jomvu",
      "Kisauni",
      "Likoni",
      "Mvita",
      "Nyali",
    ],
  },
  {
    code: "NAK",
    name: "Nakuru",
    constituencies: [
      "Bahati",
      "Gilgil",
      "Kuresoi North",
      "Kuresoi South",
      "Molo",
      "Naivasha",
      "Nakuru East",
      "Nakuru West",
      "Njoro",
      "Rongai",
      "Subukia",
    ],
  },
  {
    code: "NAN",
    name: "Nandi",
    constituencies: ["Aldai", "Chesumei", "Emgwen", "Mosop", "Tinderet"],
  },
  {
    code: "NAR",
    name: "Narok",
    constituencies: [
      "Emurua Dikirr",
      "Kilgoris",
      "Narok East",
      "Narok North",
      "Narok South",
    ],
  },
  {
    code: "NUY",
    name: "Nyamira",
    constituencies: [
      "Borabu",
      "Kitutu Masaba",
      "North Mugirango",
      "West Mugirango",
    ],
  },
  {
    code: "NYA",
    name: "Nyandarua",
    constituencies: [
      "Kinangop",
      "Kipipiri",
      "Ndaragwa",
      "Ol'Kalou",
      "Ol Jorok",
    ],
  },
  {
    code: "NYE",
    name: "Nyeri",
    constituencies: [
      "Kieni",
      "Mathira",
      "Mukurweini",
      "Nyeri Town",
      "Othaya",
      "Tetu",
    ],
  },
  {
    code: "SIA",
    name: "Siaya",
    constituencies: ["Alego Usonga", "Gem", "Rarieda", "Ugenya", "Ugunja"],
  },
  {
    code: "TAI",
    name: "Taita-Taveta",
    constituencies: ["Mwatate", "Taveta", "Voi", "Wundanyi"],
  },
  {
    code: "TAI",
    name: "Tana River",
    constituencies: ["Bura", "Galole", "Garsen"],
  },
  {
    code: "THA",
    name: "Tharaka-Nithi",
    constituencies: ["Chuka/Igambang'ombe", "Maara", "Tharaka"],
  },
  {
    code: "TUR",
    name: "Turkana",
    constituencies: [
      "Kacheliba",
      "Loima",
      "Turkana Central",
      "Turkana East",
      "Turkana North",
      "Turkana South",
      "Turkana West",
    ],
  },
  {
    code: "WAS",
    name: "Wajir",
    constituencies: [
      "Eldas",
      "Tarbaj",
      "Wajir East",
      "Wajir North",
      "Wajir South",
      "Wajir West",
    ],
  },
  {
    code: "WES",
    name: "West Pokot",
    constituencies: [
      "Kacheliba",
      "Pokot South",
      "Sigor",
      "Turkana North",
      "Turkana South",
      "Turkana West",
    ],
  },
  {
    code: "NBO",
    name: "Nairobi",
    constituencies: [
      "Westlands",
      "Kasarani",
      "Embakasi East",
      "Embakasi South",
      "Embakasi North",
      "Embakasi West",
      "Starehe",
      "Mathare",
      "Kibra",
      "Lang'ata",
      "Dagoretti North",
      "Dagoretti South",
      "Roysambu",
      "Ruaraka",
      "Makadara",
    ],
  },
];
